-- 建立預設資料庫
CREATE DATABASE `fas` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */;

-- 內網使用帳號
GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.%.%' IDENTIFIED BY PASSWORD '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' WITH GRANT OPTION;
GRANT PROXY ON ''@'%' TO 'root'@'192.168.%.%' WITH GRANT OPTION;

-- docker
GRANT USAGE ON `fas`.* TO 'fas_admin'@'172.%.%.%' IDENTIFIED BY "password" WITH MAX_QUERIES_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT GRANT OPTION ON `fas`.* TO 'fas_admin'@'172.%.%.%';
GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, EXECUTE, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `fas`.* TO 'fas_admin'@'172.%.%.%';