FROM git888.phoenix-5.com:1717/gino/docker/devops_php_laravel:v0.0.6

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install curl build-essential unzip

RUN mkdir -p /tmpbuild/libsodium && \
    cd /tmpbuild/libsodium && \
    curl -L https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz -o libsodium-1.0.16.tar.gz && \
    tar xfvz libsodium-1.0.16.tar.gz && \
    cd /tmpbuild/libsodium/libsodium-1.0.16/ && \
    ./configure && \
    make && make check && \
    make install && \
    mv src/libsodium /usr/local/ && \
    rm -Rf /tmpbuild/
# Add Microsoft repo for Microsoft ODBC Driver 13 for Linux
RUN apt-get update && apt-get install -y curl \
    apt-transport-https \
    && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/8/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update

# Install Dependencies
RUN ACCEPT_EULA=Y apt-get install -y \
    unixodbc \
    unixodbc-dev \
    libgss3 \
    odbcinst \
    msodbcsql \
    locales \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen

# Install pdo_sqlsrv and sqlsrv from PECL. Replace pdo_sqlsrv-4.1.8preview with preferred version.
RUN pecl install pdo_sqlsrv-4.1.8preview sqlsrv-4.1.8preview \
    && docker-php-ext-enable pdo_sqlsrv sqlsrv

#install zeromq
RUN \
    mkdir -p /tmpbuild/zeromq && \
    cd /tmpbuild/zeromq && \
#    curl -sSo zeromq.tar.gz http://download.zeromq.org/zeromq-4.1.4.tar.gz && \
    wget https://archive.org/download/zeromq_4.1.4/zeromq-4.1.4.tar.gz && \
    tar -xvf zeromq-4.1.4.tar.gz && \
    cd zeromq-4.1.4/ && \
    ./configure && \
    make && \
    make install && \
    rm -Rf /tmpbuild/ && \
    yes '' | pecl install zmq-beta && \
    echo "extension=zmq.so" >> $PHP_INI_DIR/conf.d/zmq.ini

WORKDIR /var/www/html
ENTRYPOINT ["docker-php-entrypoint"]
CMD ["php-fpm","-R"]
